### ISSUE TITLE
Back button behaviour logic research and proposal

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-ID#316]
What happens when the user presses the button their phone on each screen? are they sent back to the previous screen or not, Or are they sent to a different screen. This task will find the answer to these questions. Developers can Implement the logic based on this information.

Definition of done:

- [x] Document / flow diagram exists which shows what happens when the user presses the button on their phone in different screens/scenarios

**Comment by MilicaSequeira** [comment]
Rules used:
1. When having an open overlay, accordion checkout, filter... back should close them not go to the previous page thats in the back
2. Dont pollute API History with different states. When a user clicks through a gallery, or goes and clicks checkboxes, toggles... dont go back to the previous state but prevuous page.
3. Whenever a user is likely to lose data by going back its a good idea to use  a prompt to confirm their actions.
4. If a user is in the middle of a product list, then he clicks on a product to see details then clicks back, dont take him to the beginning of the page but to the part he was on when he clicked on the specific product.
5. If a user is on a multistep process e.g. shipping estimate its better if the backbutton takes them to the previous page because if the number of steps is 3 the user will have to do 3 click-backs before getting to the previous page but if there were 7 steps....
6. Use the logic of overlays for expanded objects like thumbnail image zoomed in look
7. WHen using anchor links- like on Amazon top page you click starts (review) it will jump you to the bottom of the page where the comment section is so the logic should be back button takes you to the top page. If the user scrolled from the top to the bottom of the same page the back takes them to the previous page.
8. Product variations should be combined into one product list item. e.g. Car website - looking at a specific car, listing all the colors. When the user pressed the back button it should take the user to the previous page not through all the car color variations the user clicked through. Important to point out it should return the user on the same position in the product page he was on when he clicked on the car.
