### ISSUE TITLE
Pin number and fingerprint screen show in login again

### ISSUE THREAD

**Issue by sadiabbasi** [Tonomy-Foundation/Tonomy-ID#570]
Testing and reporting process: <https://www.notion.so/tonomy-foundation/Tonomy-ID-3960924e3e324c28b5a11ba465c22a99?p=4a084f9e43df413695425289ca017446&showMoveTo=true>

## Steps to replicate the issue

1. I open app for the first time
2. I click through the **three splash screens**
3. I press on "Create Account" button on the **Create account screen**
4. I setup the pin number and confirm pin and then i skip the fingerprint screen
5. I go to user home and then from sidebar menu i logout
6. I go to login and enter the username password
7. It again show me pin number and confirm pin screen

## What do you expect to happen?

1. When we login we don't need to show the pin number screen again

- Operating system: Android 11

**Comment by theblockstalk** [comment]
this is not a bug, this is the intended behaviour. Because the PIN and Biometric data are stored locally on the device only, if you log out then that data is no longer available and it needs to be recreated. That is why every time you log in again you (optionally) need to create a new PIN and biometrics If you want to use these.
