### ISSUE TITLE
check demo site and Tonomy id for all links refereeing to the blockchain

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-ID#751]
Acceptance Criteria: 

- [x] all links  referring to the block explorer working on staging tonomy id
- [x] all links  referring to the block explorer working on staging demo app
- [x] all links  referring to the block explorer working on development demo app

**Comment by theblockstalk** [comment]
the issue is not about the links, but that we don't have history API anymore with leap v3
![image.png](https://images.zenhubusercontent.com/5ea82b5959354f2b8ef14f5d/a1962854-11e6-4409-a141-58dbda76a5f3)

see for more details:
https://github.com/Tonomy-Foundation/Tonomy-ID/issues/636#issuecomment-1508917764
